# Generated by Django 3.2.9 on 2021-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('last_appointment_id', models.BigIntegerField(blank=True)),
                ('last_appointment_date', models.DateTimeField(blank=True)),
                ('warning_sms_date', models.DateTimeField(blank=True)),
                ('first_sms_date', models.DateTimeField(blank=True)),
                ('second_sms_date', models.DateTimeField(blank=True)),
                ('cancel_by_customer', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
