# Generated by Django 3.2.9 on 2021-11-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_sms', models.TextField(blank=True)),
                ('first_sms_text', models.TextField(blank=True)),
                ('second_sms_text', models.TextField(blank=True)),
                ('seven_days', models.TextField(blank=True)),
                ('zero_days', models.TextField(blank=True)),
                ('final_warning_7_days_after', models.TextField(blank=True)),
            ],
        ),
    ]
