# Generated by Django 3.2.9 on 2021-11-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainsetup',
            old_name='final_warning_7_days_after',
            new_name='final_warning_7_days_sms_date',
        ),
        migrations.RenameField(
            model_name='mainsetup',
            old_name='first_sms_text',
            new_name='first_sms_date',
        ),
        migrations.RenameField(
            model_name='mainsetup',
            old_name='second_sms_text',
            new_name='one_year_sms_date',
        ),
        migrations.RenameField(
            model_name='mainsetup',
            old_name='seven_days',
            new_name='second_sms_date',
        ),
        migrations.RenameField(
            model_name='mainsetup',
            old_name='zero_days',
            new_name='third_sms_date',
        ),
    ]
