# Generated by Django 3.2.9 on 2021-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_mainsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsetup',
            name='update_all_users',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
