# Generated by Django 3.2.9 on 2021-11-18 03:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20211117_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 18, 3, 40, 22, 14120, tzinfo=utc), null=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('customer_info', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
