# Generated by Django 3.2.9 on 2021-11-18 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_logivents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logivents',
            name='creat',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
