# Generated by Django 3.2.9 on 2021-11-15 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_mainsetup_update_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='final_warning_7_days_sms',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 19, 35, 33, 396770)),
        ),
        migrations.AddField(
            model_name='customer',
            name='seven_days_sms',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 19, 35, 33, 396770)),
        ),
        migrations.AddField(
            model_name='customer',
            name='zero_days_sms',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 19, 35, 33, 396770)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_sms_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 19, 35, 33, 396770)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='second_sms_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 19, 35, 33, 396770)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='warning_sms_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 19, 35, 33, 396770)),
        ),
    ]
