# Generated by Django 3.2.9 on 2021-11-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_logivents_creat'),
    ]

    operations = [
        migrations.AddField(
            model_name='logivents',
            name='message_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
