# Generated by Django 3.2.9 on 2021-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_logivents_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logivents',
            name='customer_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logivents',
            name='message_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logivents',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
