# Generated by Django 3.2.9 on 2021-11-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_reportrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='final_warning_7_days_sms_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_sms_date',
        ),
    ]
