# Generated by Django 3.2.9 on 2021-11-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_auto_20211119_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logivents',
            name='customer_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logivents',
            name='message_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logivents',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
