# Generated by Django 3.2.9 on 2021-11-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20211120_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsetup',
            name='final_warning_7_days_sms_date',
        ),
        migrations.RemoveField(
            model_name='mainsetup',
            name='first_sms_date',
        ),
    ]
