# Generated by Django 3.2.9 on 2021-12-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20211121_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sms.customer')),
                ('feedback_url_1', models.TextField(blank=True, null=True)),
                ('feedback_url_2', models.TextField(blank=True, null=True)),
                ('feedback_url_3', models.TextField(blank=True, null=True)),
                ('feedback_url_click_number', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
