# Generated by Django 3.2.9 on 2021-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_feedback_feedbackurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Feedback_sms', models.TextField(blank=True, null=True)),
                ('second_Feedback_sms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackURL',
        ),
    ]
