# Generated by Django 3.2.9 on 2021-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_auto_20211204_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksmstemplate',
            name='sent_sms',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
