# Generated by Django 3.2.9 on 2021-12-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_feedbacksmstemplate_sent_sms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
