# Generated by Django 3.2.9 on 2021-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_zenticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenticket',
            name='zen_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
