# Generated by Django 3.2.9 on 2021-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_alter_zenticket_zen_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsetup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
