# Generated by Django 3.2.9 on 2021-12-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_mainsetup_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsetup',
            name='update_all_users',
        ),
    ]
