# Generated by Django 3.2.9 on 2021-12-24 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_remove_mainsetup_update_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenticket',
            name='creat',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
