# Generated by Django 3.2.9 on 2022-09-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0021_emailreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailreport',
            name='unsubscribe_status_include',
        ),
    ]
